CC = gcc

all: ransomware decryptor

ransomware: ransomware.c
	$(CC) ransomware.c -o ransomware

decryptor: decryptor.c
	$(CC) decryptor.c -o decryptor

clean:
	rm decryptor ransomware

.PHONY: clean all
